package.json
pnpm-lock.yaml

Added Biome.js as a development dependency to the project.
- Added `@biomejs/biome` version 1.9.4 as a development dependency in package.json
- Updated pnpm-lock.yaml with the new dependency and its platform-specific binaries
1. Run `pnpm install` to install the new dependency
2. Verify that Biome.js is available by running a command like `pnpm biome --version`
3. Ensure that existing build and check scripts continue to work as expected
Biome.js is a fast formatter and linter for JavaScript and TypeScript projects. Adding it as a dependency will help maintain consistent code style and catch potential issues early in the development process. This tool will improve code quality and developer experience across the project.

Add @biomejs/biome v1.9.4 as a dev dependency

---

apps/web/convex/_generated/api.d.ts
apps/web/convex/message.ts
apps/web/convex/schema.ts
apps/web/package.json
pnpm-lock.yaml

Added message functionality and enhanced schema with improved data structures for chat history, message attempts, and user preferences.
- Created a new `message.js` module with three functions:
- `sendMessage`: Mutation for sending messages
- `listMessages`: Query for retrieving messages
- `generateAiResponse`: Internal action for AI responses
- Enhanced schema with more detailed structures:
- Improved chat visibility options (private, shared, public)
- Renamed `chatMembers` to `chatMember` table
- Added comprehensive message history tracking with attempt indexing
- Added block-level version history with metadata
- Enhanced user preferences (default provider, model, theme, language)
- Added support for API key storage
- Added attachment text extraction capability
- Added OpenRouter AI SDK …

feat(web): pre mature giga-scale schema

---

apps/web/package.json
pnpm-lock.yaml

Added AI SDK integration with OpenRouter provider to the web application.
- Added `@ai-sdk/react` package (v1.2.12) for React integration with AI capabilities
- Added `@openrouter/ai-sdk-provider` package (v0.7.1) to connect with OpenRouter's AI services
- Added `zod` package (v3.25.56) as a dependency, which is required by the AI SDK for schema validation
1. Run `pnpm install` to install the new dependencies
2. Verify that the application builds successfully with `pnpm build`
3. Test any AI-related features that will be implemented using these packages
This change lays the groundwork for integrating AI capabilities into the web application using OpenRouter as the AI provider. The AI SDK will enable features like chat completions, text generation, and other AI-powered functionality while …

chore(web): add ai sdk

---

apps/web/src/lib/openrouter.ts
apps/web/src/routes/api/chat.ts
apps/web/src/routes/index.tsx

Added chat functionality using OpenRouter API with Gemini 2.0 Flash Lite model.
- Created a new OpenRouter client configuration in `lib/openrouter.ts`
- Implemented a new chat API endpoint at `/api/chat.ts` that:
- Authenticates users before allowing chat access
- Uses a system prompt that defines the chat assistant as "OpenYap"
- Streams responses from Gemini 2.0 Flash Lite model
- Enhanced the home page UI to:
- Display chat messages with different styling for user vs. assistant
- Add a functional chat input form that submits messages to the API
- Implement the `useChat` hook from AI SDK to manage chat state
1. Ensure you have an OpenRouter API key set in your environment variables
2. Log in to the application
3. Type a message in the chat input and press enter
4. Verify that the …

Add OpenRouter integration with Gemini chat functionality

---

apps/web/src/components/chatView.tsx
apps/web/src/routes/__root.tsx

Enhanced the chat UI with a modern messaging interface and improved layout structure.
- Redesigned the chat interface with a modern bubble-style message layout
- Added visual indicators for message streaming with animated dots
- Improved the input area with proper styling and disabled states
- Added support for sending messages with Enter key
- Implemented empty state for when no messages exist
- Added loading animation for the send button during message submission
- Restructured the app layout with proper header and sidebar integration
- Added clear input after message submission with the new `setInput` function
1. Open the chat interface and verify the new bubble-style message layout
2. Test sending messages and observe the input clearing after submission
3. Check that pressing Enter …

feat(web): new chat ui

---

apps/web/convex/functions/chat.ts
apps/web/convex/functions/message.ts
apps/web/src/components/chat-view.tsx

Added chat update functionality and improved error handling in chat-related operations.
- Added a new `updateChat` mutation to allow modifying chat properties (title, tags, description, visibility, etc.)
- Improved error handling in chat functions by returning empty arrays instead of throwing errors for unauthorized requests
- Refactored the message update logic to use a more maintainable approach with a dynamic patch object
- Modified the chat creation flow to set a generic "New Chat" title initially, then generate and update the title after the first message is sent
- Removed a TODO comment for handling unauthorized sessions in `getUserChats`
1. Create a new chat and verify it initially has the title "New Chat"
2. Send a message and confirm the title is automatically updated based on …

fix(web): hey chat

---

apps/web/src/components/chat-view.tsx

Improved chat UI with better styling and layout for messages.
- Refactored the chat view component with updated styling using the design system
- Changed background colors to use theme variables (`bg-background`, `text-foreground`, etc.)
- Added a max width container with centered content for better readability
- Improved message styling with different visual treatment for user messages vs assistant messages
- Fixed code formatting and indentation
2. Send messages back and forth with the assistant
3. Verify that user messages appear with the sidebar accent color on the right
4. Verify that assistant messages appear as plain text on the left
5. Check that the typing indicator shows correctly when messages are streaming
6. Confirm the layout is centered with …

feat(web): update chat view styling

---

apps/web/convex/functions/message.ts
apps/web/convex/schema.ts
apps/web/src/components/app-sidebar.tsx
apps/web/src/components/blocks.tsx
apps/web/src/components/chat-view.tsx
apps/web/src/routes/api/chat.ts
apps/web/vite.config.ts

Enhanced message history tracking and user preferences structure while improving UI elements in the chat interface.
- Added support for tracking model and provider information in AI messages
- Added history entry tracking for AI messages with version control
- Restructured user preferences into a nested object structure
- Improved sidebar UI with better hover states for chat items
- Fixed chat view to properly handle loading states
- Updated Vite configuration to target Vercel deployment
- Enhanced the message update API to include model, provider, and history information
1. Create a new chat and observe the improved UI in the sidebar
2. Check that the chat view properly displays a loading state when fetching messages
3. Send messages and verify that model and provider information is …

feat(web): small ui updates and ai message history

---

apps/web/src/components/chat-view.tsx
apps/web/src/components/chat/chat-input.tsx

Refactored chat components to improve performance and code organization by implementing memoization and optimizing callback functions.
- Added memoization to the `ChatInput` component using `memo` from React
- Extracted `ModelSelector` into a separate memoized component
- Wrapped event handlers and functions in `useCallback` to prevent unnecessary re-renders
- Improved code formatting and readability with proper indentation
- Fixed potential performance issues by memoizing functions that were being recreated on each render
- Added proper type definitions for streaming messages
- Restructured the `addUserMessage` function to use `useCallback`
1. Open the chat interface and verify that all functionality works as before
2. Test sending messages and observe that the UI remains responsive
3. …

feat(web): memoized chat input

---

apps/web/convex/functions/message.ts
apps/web/convex/schema.ts
apps/web/package.json
apps/web/src/components/blocks.tsx
apps/web/src/components/chat-view.tsx
apps/web/src/components/chat/types.ts
apps/web/src/components/message.tsx
apps/web/src/components/ui/animated-shiny-text.tsx
apps/web/src/components/ui/collapsible.tsx
apps/web/src/routes/api/chat.ts
apps/web/src/styles.css
pnpm-lock.yaml

Added reasoning steps to AI messages with a collapsible UI component to show the AI's thought process.
- Added a `reasoning` field to message schema with steps that track the AI's thought process
- Added `status` field to track message states like "reasoning", "generating", and "finished"
- Renamed `toolCalls` to `tools` and `citations` to `sources` for better semantics
- Created a collapsible UI component to display reasoning steps with timestamps
- Added streaming support for reasoning steps in the chat API
- Implemented an animated "Thinking" indicator when AI is reasoning
- Added proper typing for message-related structures
1. Start a conversation with the AI
2. Observe the "Thinking" indicator when the AI is processing
3. Click on the "Thought" collapsible to expand and see the AI's …

feat(web): thinking

---

apps/web/src/components/blocks.tsx

Enhanced code block styling and fixed heading rendering issues.
- Reduced syntax highlighting delay from 1000ms to 750ms for faster code rendering
- Improved code block styling:
- Added consistent font family using Fira Code/Mono with fallbacks
- Enhanced non-highlighted code appearance with better styling
- Applied proper styling to pre/code elements with consistent font, spacing, and colors
- Fixed overflow handling for code blocks
- Fixed heading rendering:
- Removed unnecessary whitespace in JSX
- Fixed a bug in h4 elements where "-900 shadow" text was incorrectly included
- Added proper spacing between elements
1. View pages with code blocks to verify the improved styling and faster highlighting
2. Check that code blocks properly handle overflow content
3. Verify headings render …

feat(web): improve code block styling and reduce highlight delay

---

apps/web/src/components/app-sidebar.tsx
apps/web/src/components/auth/profile-card.tsx
apps/web/src/components/chat/chat-toggles.tsx
apps/web/src/components/chat/model-selector.tsx
apps/web/src/components/chat/reasoning-effort-selector.tsx
apps/web/src/components/ui/button.tsx
apps/web/src/components/ui/prompt-input.tsx
apps/web/src/components/ui/select.tsx

Improved UI styling for better visual consistency and user experience across the application.
- Added left padding (`pl-1`) to chat titles in the sidebar for better text alignment
- Enhanced button styling with `hover:cursor-pointer` for better hover state feedback
- Removed borders and shadows from UI controls (model selector, reasoning effort selector, and chat toggles) for a cleaner look
- Made the profile card more visually appealing with rounded corners
- Fixed background transparency issues in dark mode for various components
- Improved the layout of the ProfileAvatar component for better readability
- Ensured consistent styling for interactive elements across the application
1. Check the sidebar chat titles to ensure proper padding and alignment
2. Verify hover states on buttons …

style(web): improve UI with consistent styling and hover states

---

apps/web/src/components/chat/chat-view.tsx
apps/web/src/components/chat/message.tsx
apps/web/src/components/chat/types.ts
apps/web/src/hooks/use-chat.ts

Refactored chat message handling to improve performance and user experience with better state management and animations.
- Replaced `streamingMessage` state with improved message status tracking directly in the messages array
- Introduced a `ChatStatus` enum to better manage chat states (IDLE, LOADING, STREAMING)
- Added a loading indicator with animated shiny text when messages are being processed
- Memoized message components to reduce unnecessary re-renders
- Enhanced the reasoning collapsible component with smooth animations
- Simplified message rendering logic in the chat view
- Updated the message append function to handle state transitions more efficiently
- Removed the separate `StreamingAiMessage` component in favor of a unified approach
- Fixed styling consistency for message …

feat(web): better chat streaming

---

apps/web/src/components/chat/chat-view.tsx

Added a scroll-to-bottom button that appears when users scroll away from the bottom of the chat.
- Added a new "scroll to bottom" button with an arrow icon that appears when the user scrolls away from the bottom of the chat
- Implemented an IntersectionObserver to detect when the user has scrolled away from the bottom
- The button has a smooth transition effect (fades in/out based on scroll position)
- Removed the automatic scroll behavior that previously occurred on every message load
- Added hover effects to the button that change its background and text colors
1. Open a chat with several messages
2. Scroll up in the conversation
3. Verify that the arrow button appears with a smooth transition
4. Click the button and confirm it smoothly scrolls back to the bottom
5. Scroll to the bottom …

feat(web): add scroll-to-bottom button in chat view

---

apps/web/src/lib/models.ts

Added markdown formatting requirements to the system prompt.
Added two new instructions to the system prompt in `models.ts`:
- Format all links as markdown links with an example provided
- Only use markdown formatting for text formatting
1. Verify that the system prompt now includes the new formatting instructions
2. Test that the model properly formats links as markdown links
3. Confirm that text formatting is done using markdown syntax only
To ensure consistent formatting in responses, particularly for links and text styling, by explicitly instructing the model to use markdown formatting standards.

feat(web): update system prompt

---

apps/web/src/components/chat/model-selector.tsx

Replaced the model selector dropdown with a searchable command palette.
- Replaced the basic `Select` component with a more advanced `Popover` + `Command` component combination
- Added search functionality to filter models by name or company
- Improved the UI with a cleaner layout and visual indicators for the selected model
- Added a check mark icon to clearly indicate the currently selected model
- Implemented a custom filter function to improve search relevance
- Changed from `useCallback` to `useState` to manage the popover open state
2. Click on the model selector button
3. Verify that the command palette opens with a search input
4. Try searching for models by name or company
5. Select a model and confirm it's properly highlighted with a check mark
6. …

feat(web): model selector upgrades

---

apps/web/src/components/auth/profile-card.tsx
apps/web/src/components/chat/chat-input.tsx
apps/web/src/components/chat/chat-view.tsx
apps/web/src/components/chat/file-attachment-button.tsx
apps/web/src/components/chat/reasoning-effort-selector.tsx
apps/web/src/components/ui/prompt-input.tsx
apps/web/src/hooks/use-chat.ts
apps/web/src/hooks/use-file-attachments.ts
apps/web/src/hooks/use-file-drop.ts
apps/web/src/lib/ai/webSearch.ts
apps/web/src/lib/logger.ts
apps/web/src/lib/models.ts
apps/web/src/routes/api/chat.ts

Applied consistent code formatting across the codebase using Prettier.
This PR applies consistent code formatting to multiple files throughout the codebase using Prettier. The changes include:
- Consistent trailing commas in function parameters and array/object literals
- Proper indentation and line breaks for multiline statements
- Organized imports (alphabetical ordering in some cases)
- Consistent spacing around operators and in object literals
- Standardized string quotes and template literals
- Reformatted the logger.ts file with proper spacing and consistent styling
1. Run the application to ensure all functionality works as expected
2. Verify that the code builds without any errors
3. Check that the logger outputs messages correctly in both browser and Node environments
4. Confirm …

lint(web): fix

---

apps/web/src/hooks/use-chat.ts

Fixed chat switching behavior to properly handle in-progress streaming when navigating between chats.
- Added a `currentChatId` state to track the active chat and detect chat switches
- Implemented proper cleanup when switching between chats:
- Abort any in-progress streaming
- Clear messages
- Reset chat status
- Added checks throughout the streaming process to ensure updates only apply to the current chat
- Split the effects to separately handle chat switching and message updates
- Added safeguards to prevent state updates for inactive chats
1. Open a chat and send a message to start streaming a response
2. While the AI is still responding, quickly navigate to a different chat
3. Verify that:
- The previous streaming is aborted
- The new chat loads correctly without showing content from …

fix(web): chat switch bug while stream

---

apps/web/package.json
apps/web/src/components/app-sidebar.tsx
apps/web/src/components/chat/chat-input.tsx
apps/web/src/components/chat/chat-view.tsx
apps/web/src/components/ui/sidebar.tsx
apps/web/src/hooks/use-mobile.ts
apps/web/src/hooks/use-responsive-sidebar.ts
apps/web/src/styles.css
pnpm-lock.yaml

Enhanced the chat UI with improved scrolling behavior, responsive sidebar, and better layout for different screen sizes.
- Added `tailwind-scrollbar` package for custom scrollbar styling
- Improved chat view scrolling behavior:
- Replaced intersection observer with scroll position detection
- Added custom scrollbar styling with hover effects
- Fixed scroll-to-bottom button behavior
- Enhanced sidebar responsiveness:
- Created new `useResponsiveSidebar` hook to manage sidebar state based on screen size
- Added cursor-e-resize to collapsed sidebar for better UX
- Added "no-scrollbar" utility class
- Adjusted layout dimensions:
- Changed chat container max width from `max-w-3xl` to `max-w-[752px]`
- Updated mobile breakpoint from 768px to 816px
- Added medium screen detection (between mobile …

feat(web): ui enhancements

---

apps/web/src/lib/ai/mathEvaluation.ts
apps/web/src/lib/models.ts

- Optimized math evaluation tool performance by simplifying Effect-TS usage patterns
- Added comprehensive logging for better debugging and monitoring
- Enhanced system prompt with math result formatting instructions
- **Performance improvements**: Removed redundant `parse()` call and simplified Effect-TS from `tryPromise + pipe` to `try + runSync` pattern
- **Better constants**: Replaced confusing `UI_CONSTANTS.POLLING_INTERVALS.SLOW_UPDATE` with clear `MAX_RESULT_LENGTH = 1000`
- **Comprehensive logging**: Added detailed logging for successful evaluations and specific error types (equations, undefined symbols, general errors)
- **Code clarity**: Removed unnecessary imports (`pipe` from effect/Function, `parse` from mathjs)
- **System prompt enhancement**: Added instruction to format …

Optimize math evaluation tool performance and logging

---

apps/web/src/components/chat/chat-view.tsx
apps/web/src/lib/models.ts
apps/web/src/routes/__root.tsx
apps/web/src/styles.css

- Fixed mobile chat input being covered by browser UI and keyboard
- Improved layout structure for better mobile responsiveness
- Added safe area padding support for devices with notches
- Changed chat view layout from absolute positioning to flexbox for better mobile support
- Used dynamic viewport height (`h-dvh`) on mobile to account for browser chrome
- Added safe area insets for proper padding on iOS devices
- Updated viewport meta tag to include `viewport-fit=cover`
- Ensured chat input remains visible and accessible at all times on mobile

fix: mobile browser covering chat input
